server:
  port: 8080

spring:
  application:
    name: paimana-insight

  datasource:
    url: jdbc:dpg-darcpf3tqb8s73f03s9g-a://localhost:5432/ppaimana_insight
    username:paimana_insight_user
    password:GxMFr4EjD83ewBVIvvHLoYg86wI2HnkQ

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret:A new random secret of 32+ characters
    expiration-ms: 86400000

  ml:
    base-url: http://localhost:8001
